ruby '2.3.1'
source 'https://rubygems.org'
gem 'sinatra', require: false
gem 'sinatra-contrib', require: false
gem 'rack-contrib'
gem 'puma'
gem 'rake'
gem 'sass'
gem 'airmodel', path: '/Users/chrisfrank/code/airmodel'
gem 'memcachier'
gem 'dalli'
gem 'rack-cache'
gem 'sprockets'
gem 'sprockets-helpers', require: 'sinatra/sprockets-helpers'
gem 'redcarpet'
group :development, :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rerun'
  gem 'capybara-webkit'
  gem 'pry'
  gem 'dotenv'
  gem 'launchy'
  gem 'fakeweb'
end
